import os

files = []
files.append({"file": "Report_h8.pdf",      "target": "LH_2",     "Q2": 8.0})
files.append({"file": "Report_h95sm.pdf",   "target": "LH_2",     "Q2": 9.5})
files.append({"file": "Report_h115.pdf",    "target": "LH_2",     "Q2": 11.5})
files.append({"file": "Report_h143.pdf",    "target": "LH_2",     "Q2": 14.2})
files.append({"file": "Report_c12_8.pdf",   "target": "{}^{12}C", "Q2": 8.0})
files.append({"file": "Report_c95.pdf",     "target": "{}^{12}C", "Q2": 9.5})
files.append({"file": "Report_c115.pdf",    "target": "{}^{12}C", "Q2": 11.5})
files.append({"file": "Report_c143_sm.pdf", "target": "{}^{12}C", "Q2": 14.2})

"Report_h8.pdf"
"Report_h95sm.pdf"
"Report_h115.pdf"
"Report_h143.pdf"

Q2=(8, 9.5, 11.5, 14.2)

appendix_file = open("../appendices/data_and_simc_distributions.tex","w")
appendix_file.write("\chapter{Comparison of Experimental and Monte Carlo Distributions} \label{app:distributions}\n")
appendix_file.write("This appendix compares the distributions of reconstructued quantities measured in experiment\n")
appendix_file.write("to those generated by SIMC.\n")
appendix_file.write("Error bars are statistical only and the distributions are normalized to each other.\n")

for file in files:
    # HMS quantities are on page 1
    appendix_file.write("\\begin{figure}[!h]\n")
    appendix_file.write("    \centering\n")
    appendix_file.write("    \includegraphics[page=1,width=1.0\\textwidth]{pass5_report/%s}\n" % file["file"])
    appendix_file.write("    \caption{\n")
    appendix_file.write("            Experimental (in blue) and Monte Carlo (in red) distributions of\n")
    appendix_file.write("            target quantities reconstructed from the HMS for\n")
    appendix_file.write("            the $%s$ target at $Q^2=\SI{%.1f}{\giga\electronvolt\squared}$.\n" % (file["target"],file["Q2"]))
    appendix_file.write("            }\n")
    appendix_file.write("    \label{fig:%s_pg1}\n" % file["file"])
    appendix_file.write("\end{figure}\n")
    appendix_file.write("\n")
    appendix_file.write("\n")

for file in files:
    # SHMS quantities are on page 2
    appendix_file.write("\\begin{figure}[!h]\n")
    appendix_file.write("    \centering\n")
    appendix_file.write("    \includegraphics[page=2,width=1.0\\textwidth]{pass5_report/%s}\n" % file["file"])
    appendix_file.write("    \caption{\n")
    appendix_file.write("            Experimental (in blue) and Monte Carlo (in red) distributions of\n")
    appendix_file.write("            target quantities reconstructed from the SHMS for\n")
    appendix_file.write("            the $%s$ target at $Q^2=\SI{%.1f}{\giga\electronvolt\squared}$.\n" % (file["target"],file["Q2"]))
    appendix_file.write("            }\n")
    appendix_file.write("    \label{fig:%s_pg2}\n" % file["file"])
    appendix_file.write("\end{figure}\n")
    appendix_file.write("\n")
    appendix_file.write("\n")

for file in files:
    # physics quantities are on page 3
    appendix_file.write("\\begin{figure}[!h]\n")
    appendix_file.write("    \centering\n")
    appendix_file.write("    \includegraphics[page=3,width=1.0\\textwidth]{pass5_report/%s}\n" % file["file"])
    appendix_file.write("    \caption{\n")
    appendix_file.write("            Experimental (in blue) and Monte Carlo (in red) distributions of\n")
    appendix_file.write("            reconstructed physics quantities for\n")
    appendix_file.write("            the $%s$ target at $Q^2=\SI{%.1f}{\giga\electronvolt\squared}$.\n" % (file["target"],file["Q2"]))
    appendix_file.write("            }\n")
    appendix_file.write("    \label{fig:%s_pg3}\n" % file["file"])
    appendix_file.write("\end{figure}\n")
    appendix_file.write("\n")
    appendix_file.write("\n")

appendix_file.close()
